name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    tests:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15-alpine
                env:
                    POSTGRES_USER: symfony
                    POSTGRES_PASSWORD: symfony
                    POSTGRES_DB: symfony_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd "pg_isready -U symfony"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    extensions: mbstring, intl, pdo_pgsql
                    ini-values: post_max_size=256M, upload_max_filesize=256M
                    coverage: none

            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-

            -   name: Install dependencies
                run: composer install --no-interaction --prefer-dist

            -   name: Create test database schema
                env:
                    DATABASE_URL: "postgresql://symfony:symfony@localhost:5432/symfony_test?serverVersion=15&charset=utf8"
                run: |
                    php bin/console doctrine:database:create --if-not-exists --env=test
                    # php bin/console doctrine:schema:update --force --env=test
                    php bin/console doctrine:migrations:migrate --no-interaction --env=test

            -   name: Run Symfony tests
                env:
                    APP_ENV: test
                    DATABASE_URL: "postgresql://symfony:symfony@localhost:5432/symfony_test?serverVersion=15&charset=utf8"
                run: |
                    ./vendor/bin/phpunit --testdox
